checks:
  doNotAutoAddDefaults: true
  include:
    - "privileged-container"
    - "run-as-non-root"
    - "sensitive-host-mounts"
    - "readiness-port"
    - "non-existent-service-account"
    - "mismatching-selector"
    - "latest-tag"
