---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: media
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jellyfin
  name: jellyfin
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jellyfin
    spec:
      containers:
      - image: jellyfin/jellyfin:1.0 # version place holder 7 DEC 2025
        name: jellyfin
        resources: {}
        volumeMounts:
        - mountPath: /media
          name: media-vol
        - mountPath: /media1
          name: media-vol1
        - mountPath: /media2
          name: media-vol2
      volumes:
      - name: media-vol
        nfs:
          server: 192.168.0.106
          path: /exports/nfs_share/media1
      - name: media-vol1
        nfs:
          server: 192.168.0.106
          path: /exports/nfs_share/media2
      - name: media-vol2
        nfs:
          server: 192.168.0.106
          path: /exports/nfs_share/media3
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jellyfin
  annotations:
    external-dns.alpha.kubernetes.io/hostname: jellyfin.homelab.local
  name: jellyfin
  namespace: media
spec:
  ports:
  - port: 80 # tired of typing the port address every time
    protocol: TCP
    targetPort: 8096
  selector:
    app: jellyfin
  type: LoadBalancer
status:
  loadBalancer: {}
